#!/bin/bash
#

### BEGIN INIT INFO
# Provides:             open-garage
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    open-garage Node App
### END INIT INFO

export PATH=$PATH:/opt/node/bin
export NODE_PATH=$NODE_PATH:/opt/node/lib/node_modules

STARTBEACON="0"

case "$1" in
  start)
    if [ ! -d '/tmp/.forever' ]; then
        mkdir /tmp/.forever
    fi
	
	/opt/open-garage/garage-controller init

    forever start -a -l /tmp/forever.log -e /tmp/forever.error -p /tmp/.forever --sourceDir=/opt/open-garage garage.js
	
	if [$STARTBEACON = "1"]; then
		/opt/open-garage/beacon-controller.sh start
	fi
    ;;
  stop)
    forever stopall
	
	if [$STARTBEACON = "1"]; then
		/opt/open-garage/beacon-controller.sh stop
	fi
    ;;
  restart)
    forever restartall
    ;;
  *)

  echo "Usage: /etc/init.d/open-garage {start|stop|restart}"
  exit 1
  ;;
esac
exit 0
